/*
Kafka broker allows the consumer to read data from any available offset.
To help brokers to locate the given partition quickly, Kafka maintains an index for each partition.
An index is a mapping of offsets to segment files and its position within the file.
When messages are deleted, corresponding offset entries will be deleted from the index.
Indexes are split into segments.
When an index becomes corrupted, it will get automatically regenerated by re-reading the messages and recording the offsets
and corresponding locations.


 */
package com.mahfooz.kafka.kafka.topic.partition.index;

public class PartitionIndex {
}
